spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  profiles: dev
  application: 
<<<<<<< HEAD
    name: microservicecloud-config-atguigu-dev
=======
      name: microservicecloud-config-atguigu-dev
>>>>>>> 0887bd4d11021870d92d26c660f45126628de656
---
spring: 
  profiles: test
  application: 
<<<<<<< HEAD
    name: microservicecloud-config-atguigu-test
=======
      name: microservicecloud-config-atguigu-test
>>>>>>> 0887bd4d11021870d92d26c660f45126628de656
